//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherToday.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WeatherToday.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City list.
        /// </summary>
        public static string city_list_title {
            get {
                return ResourceManager.GetString("city_list_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit city.
        /// </summary>
        public static string edit_city_title {
            get {
                return ResourceManager.GetString("edit_city_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close app?.
        /// </summary>
        public static string message_close_app {
            get {
                return ResourceManager.GetString("message_close_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured. Restart app for continue.
        /// </summary>
        public static string message_reload_app {
            get {
                return ResourceManager.GetString("message_reload_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to metric.
        /// </summary>
        public static string metric {
            get {
                return ResourceManager.GetString("metric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:dd MMM yyyy}.
        /// </summary>
        public static string short_date {
            get {
                return ResourceManager.GetString("short_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooops!.
        /// </summary>
        public static string title_error_default {
            get {
                return ResourceManager.GetString("title_error_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather today.
        /// </summary>
        public static string weather_list_title {
            get {
                return ResourceManager.GetString("weather_list_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeatherToday.
        /// </summary>
        public static string weather_today {
            get {
                return ResourceManager.GetString("weather_today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:ddd}.
        /// </summary>
        public static string week_day_date {
            get {
                return ResourceManager.GetString("week_day_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
